### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by koooge** [szyn/docker-digdag#1]
hello. **docker-digdag** was useful for me. thank you!

README.md
```
Usage

You have to install dogdag command. ← docdag?
```

**Comment by szyn** [comment]
Hello. Thank you for your comment! I really appreciate it.
`dogdag` is not typo. It's a shell script wrapper for "docker run" command.

Please see below.
https://github.com/szyn/docker-digdag/blob/master/provision/docdag

Although dogdag is not required, but this could be helpful.

**Comment by koooge** [comment]
Aha! okay :+1:
